chore(Workflow): add coding_style checker

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -79,10 +79,48 @@ jobs:
           echo "All executables are present."
           make tests_run
 
+  check_coding_style:
+    needs: set_current_url
+    if: ${{ !contains(needs.set_current_url.outputs.current_url, github.repository) || !contains(github.repository, needs.set_current_url.outputs.current_url)}}
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: coding style checker
+        run: |
+          ls
+          check.sh $(pwd) $(pwd)
+          ls
+          FILE=coding-style-reports.log
+          if [ -s "$FILE" ]; then
+          input_file="coding-style-reports.log"
+          while IFS= read -r line; do
+          
+            filename=$(echo "$line" | cut -d ':' -f 1 | sed 's/^\.\///')
+            line_number=$(echo "$line" | cut -d ':' -f 2)
+            error_type=$(echo "$line" | cut -d ':' -f 3)
+            error_value=$(echo "$line" | cut -d ':' -f 4)
+          
+            NAME_FILE="${filename}"
+            LINE="${line_number}"
+            TYPE="${error_type}"
+            VALUE_ERROR="${error_value}"
+          
+            echo "::error file=./${NAME_FILE},line=${LINE},title=${TYPE} coding style error::${VALUE_ERROR}"
+            echo "./${NAME_FILE}:${LINE}:${TYPE}:${VALUE_ERROR}"
+          done < "$input_file"
+          exit 1
+          fi
+
   push_to_mirror:
     needs:
       - set_current_url
       - check_program_compilation
+      - check_coding_style
     if: ${{ !contains(needs.set_current_url.outputs.current_url, github.repository) || !contains(github.repository, needs.set_current_url.outputs.current_url) }} && ${{ github.event_name }} == 'push'
     runs-on: ubuntu-latest
     steps:
